### ISSUE TITLE
Unable to post comments Laravel 5.6

### ISSUE THREAD

**Issue by simonjr1** [laravelista/comments#19]
When I log in and try to connect the page just reloads but the comment is not posted to the database.
I'm using wamp for my development in Laravel

**Comment by mabasic** [comment]
Works?

**Comment by mattrabe** [comment]
I experienced the same symptom. I was using this package to attach comments to the `WinkPost` created by [writingink/wink](https://github.com/writingink/wink). The problem was that this model does not use an integer id, and therefore this package was returning a validation error. The `commentable_id` columns on the `comments` table is integer, so removing the validation check resulted in a MySQL error. Will post a PR shortly.

**Comment by mabasic** [comment]
Okey, I see the issue here. You have a table with ID of type string and this package only supports integer IDS.
