### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by robbielove** [laravelista/comments#200]
It would appear this repo is abandoned and should be denoted as such

- there have been no commits for a year
- no release for Laravel 9 compatibility
- no compatibility with Laravel 10

**Comment by mabasic** [comment]
Hi, it is not abandoned, but it is as it is currently. There is no Laravel 9 & 10 compatibility because I haven't found the time to test it and I haven't got a need to do it also. If you want, you can always send a PR which isn't just bumping dependencies but also creating a sample repository and checking the functionality of the package ...

The testing process is very difficult and I don't want to release something that isn't tested. Currently there are no tests for this package. That is one of the things that I would like to do ... but again, haven't had the time or the need for it.
